apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: acmeair-booking-db-1-vol
  labels:
     appname: acmeair
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ocs-storagecluster-ceph-rbdmirror
